chortke/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
# from django.urls import path
from django.urls import path, include

from taghaza import views

from django.utils.translation import ugettext_lazy as _




# # -*- coding: utf-8 -*-
# import xadmin
# xadmin.autodiscover()

# # version模块自动注册需要版本控制的 Model
# from xadmin.plugins import xversion
# xversion.register_models()


urlpatterns = [
                url(r'^', admin.site.urls),
                # path('/', admin.site.urls),
                path('reports', views.report, name='report'),
                # url(r'xadmin/', xadmin.site.urls),
                url(r'^_nested_admin/', include('nested_admin.urls')),
              ]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# Change admin site title
admin.site.site_header = _("سیستم مدیریت خرید‌های داخلی امور‌ تدارکات و عملیات شرکت گاز استان آذربایجان شرقی")
admin.site.site_title = _("سیستم مدیریت خرید‌های داخلی امور‌ تدارکات و عملیات شرکت گاز استان آذربایجان شرقی")

aghlam/models.py
from django.db import models
import locale

# Create your models here.
from kala.models import Kala
from sherkat.models import Sherkat
from taghaza.models import Taghaza
from django.conf import settings


class Aghlam(models.Model):
    taghaza = models.ForeignKey(Taghaza, related_query_name='taghaza', on_delete=models.DO_NOTHING,
                                verbose_name="تقاضا")
    # factor = models.ForeignKey(Factor, on_delete=models.CASCADE, verbose_name="فاکتور", null=True, blank=True, )
    kala = models.ForeignKey(Kala, on_delete=models.DO_NOTHING, verbose_name="نام کالا")
    sherkat = models.ForeignKey(Sherkat, on_delete=models.DO_NOTHING, verbose_name="تامین کننده", null=True, blank=True,)
    mablagh = models.IntegerField(verbose_name="مبلغ واحد", null=True, blank=True, )
    meghdar = models.IntegerField(verbose_name="مقدار", )
    external = models.BooleanField(verbose_name="خارجی", default=False)

    class Meta:
        verbose_name = "قلم"
        verbose_name_plural = "اقلام"

    def __str__(self):
        star = ""
        # return str(self.kala.sharh) + "|" + str(self.meghdar)+  " " + str(self.kala.vahede_andazegiri) + "|به شماره تقاضای: "+str(self.taghaza)
        if len(self.factor_set.all())!=0 :
            star = "شماره فاکتور:" + str(self.factor_set.all().first())
            # star = '-'.join([str(i) for i in self.factor_set.all()])
        return "["+str(str(self.pk) +"]["+\
            str(self.kala.sharh)  +"]["+\
            str(self.meghdar)+str(self.kala.vahede_andazegiri) +"]["+\
            "قیمت واحد:"+str(self.mablagh)+ "ریال"+"]["+\
            "مبلغ کل:" + self.mablaghe_koll_splited()).replace('None',"0")+ "ریال"+"]["+\
            star+"][" + \
            "شماره تقاضا:" + str(self.taghaza) + "]"


    def mablaghe_koll_splited(self):
        try:
            tot = self.meghdar * self.mablagh
        except:
            tot = 0
        return '{:0,.0f}'.format(tot)
        # locale.setlocale(locale.LC_ALL, 'fa')
        # return locale.currency(tot, grouping=True)
    mablaghe_koll_splited.short_description = "مبلغ کل"

    def mablaghe_koll(self):
        return int(filter(str.isdigit, self.mablaghe_koll_splited(self)))

taghaza/models.py
import locale

from django.db import models
from django.utils.safestring import mark_safe

class Taghaza(models.Model):
    vahedHa = [
        
        (0, 'امورقراردادهاوپیمانکاران'),
        (1, 'بهره‌برداری'),
        (2, 'امور رفاهی'),
        (3, 'اندازه‌گیری و توزیع گاز'),
        (4, 'حراست'),
        (5, 'خدمات طرح‌ها'),
        (6, 'گازرسانی صنایع'),
        (7, 'فناوری اطلاعات'),
        (8, 'امورتدارکات وعملیات کالا'),
        (9, 'HSE اچ اس ای'),
        (10, 'روابط عمومی'),
        (11, 'امور ورزشی'),
        (12, 'سایر واحدهای ستادی'),

    ]

    # def FileNameHandler(self):
    #     return str(self.shomare)


    # name = models.CharField(max_length=500, unique=True)
    # parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')

    shomare = models.CharField(verbose_name="شماره تقاضا", max_length=500, unique=True)
    tarikh = models.DateField(auto_now=False, auto_now_add=False, verbose_name="تاریخ تقاضا")
    sharh = models.CharField(max_length=500, null=True, verbose_name="شرح تقاضا")
    baravord = models.IntegerField(null=True, verbose_name="مبلغ براورد اولیه")
    vahed = models.IntegerField(
        verbose_name="واحد متقاضی",
        choices=vahedHa,
    )

    def user_directory_path(instance, filename):
        return 'static/pics/taghaza/{0}/{1}'.format(instance.shomare,filename)
    image = models.ImageField(verbose_name="تصویر فرم تقاضای کالا (MT26)",upload_to = user_directory_path,default='static/pics/no-pic.jpg')


    class Meta:
        verbose_name = "تقاضا"
        verbose_name_plural = "تقاضا ها"
        # app_label = 'My APP name'

    def __str__(self):
        return str(self.shomare)  # + ": " + self.sharh

    def image_tag(self):
        return mark_safe(u'<style>#imgZoom{transition: transform .25s ease;border:1px solid orange;}#imgZoom:hover {transform:rotate(90deg) scale(16,25);position: absolute;z-index:1000;border:0.1px solid lightblue;}"</style><a target="_blank"  href="/%s"><img id="imgZoom" height="20px" width="20px" src="/%s" /></a>'% (self.image,self.image))

    image_tag.short_description = 'تصویر'
    image_tag.allow_tags = True


  

    def price(self):
        # factors = self.factor_set.all()
        # total = 0
        # for factor in factors:
        #     aghlam = factor.aghlam_set.all()
        #     for ghalam in aghlam:
        #         try:
        #             total += ghalam.mablagh * ghalam.meghdar
        #         except:
        #             total += 0
        total = 0
        aghlam = self.aghlam_set.all()
        for ghalam in aghlam:
                try:
                    total += ghalam.mablagh * ghalam.meghdar
                except:
                    total += 0
        return round(total,0)

    price.short_description = "مبلغ کل"

    def count(self):
        # factors = self.factor_set.all()
        # total = 0
        # for factor in factors:
        #     aghlam = factor.aghlam_set.all()
        #     for ghalam in aghlam:
        #         total += ghalam.meghdar
        # return total


        total = 0
        aghlam = self.aghlam_set.all()
        for ghalam in aghlam:
            try:
                total += ghalam.meghdar
            except:
                total += 0
        return total



    count.short_description = "تعداد قلم"

templates/reports/ResidReport.html
{% load i18n static %}
<!DOCTYPE html> {% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
<html lang="{{ LANGUAGE_CODE|default:" en-us " }}" {% if LANGUAGE_BIDI %}dir="rtl" {% endif %}>

<head>
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/base.css" %}">
    <script src="{% static "js/jquery2.min.js" %}"></script>
    <meta name="viewport" content="width=device-width,maximum-scale=1.0">


</head>

<body style="font-family:Vazir;">
    <style>
        @media print {

            .no-print,
            .no-print * {
                display: none !important;
            }

            body {
                scale: 70%;
            }
        }


        th,
        td {
            border: 1px solid #ddd;
            vertical-align: top;
        }

        th {
            text-align: right;
        }

        table {
            border: 1px solid #ddd;
            border-collapse: collapse;
            width: 100%;
            height: 100%;

        }

        #ghalam_total {
            text-align: center;
            border: 1px solid #ddd;

        }
    </style>

    <center class="no-print">
        گزارش مجموعه تقاضا ها
        <button onclick="myFunction()">چاپ</button>
    </center>
    <table>
        <thead>
            <tr>
                <th>ردیف</th>
                <th>شماره رسید</th>
                <th>تاریخ رسید</th>
                <th>شماره تقاضا</th>
                <th>واحد متقاضی</th>
                <th>شرح تقاضا</th>
                <th>مقدار</th>
                <th>تاریخ تقاضا</th>
                <!-- <th>اقلام مورد سفارش</th>
                <th>فاکتور</th> -->
                <th>مبلغ تقاضا</th>

            </tr>
            <thead>
            <tbody>
                {% for resid in residha %}
                <tr>
                    <td> {{ resid.id }} </td>
                    <td> {{ resid.shomare }} </td>
                    <td> {{ resid.tarikh }} </td>

                    <!-- <td> {{ resid.taghaza.id }} </td> -->
                    <td> {{ resid.taghaza.shomare }} </td>
                    <td> {{ resid.taghaza.get_vahed_display }} </td>
                    <td> {{ resid.taghaza.sharh }} </td>
                    <!-- <td> {{ taghaza.type }} </td> -->
                    <td> {{ resid.taghaza.count }} </td>
                    <td> {{ resid.taghaza.tarikh }} </td>
                    <!-- <td> {{ taghaza.linkha }} </td> -->


                    <td class="price_totals">{{ resid.taghaza.price }}</td>
                </tr>
                <tr>
                    <table>
                        <tr>
                            <td>نام</td>
                            <td>مقدار</td>
                            <td>کدطبقه بندی کالا</td>
                        </tr>
                        {% for ghalam in resid.taghaza.aghlam_set.all %}
                        <tr>
                            <td>{{ ghalam.kala }}</td>
                            <td class='tghalam_totals'>{{ ghalam.meghdar }}{{ ghalam.kala.vahede_andazegiri }}</td>
                            <td>{{ghalam.kala.mesc}}</td>

                        </tr>
                        {% endfor %}

                    </table>
                </tr>

                <tr>
                    <table>
                        <tr>
                            <td>شماره فاکتور</td>
                            <!-- <td>اقلام</td> -->
                            <td>تاریخ</td>
                            <td>ارزش افزوده</td>
                            <td>مقدار</td>
                            <td>مبلغ کل</td>
                        </tr>
                        {% for factor in resid.taghaza.factor_set.all %}
                        <tr>
                            <td>{{ factor.shomare }}</td>

                            <td>{{ factor.tarikh }}</td>
                            <td class="arzeshe_afzoode">{{ factor.arzeshe_afzude }}</td>
                            <td>{{ factor.meghdar }}</td>
                            <td>{{ factor.price }}</td>
                        </tr>
                        <tr>
                            <table>
                                <tr>
                                    <td>نام</td>
                                    <td>مقدار</td>
                                    <td>فروشنده</td>
                                    <td>مبلغ</td>
                                    <td>مبلغ کل</td>
                                </tr>
                                {% for ghalam in factor.aghlam.all %}
                                <tr>
                                    <td>{{ ghalam.kala }}</td>
                                    <td class='ghalam_totals'>
                                        {{ ghalam.meghdar }}{{ ghalam.kala.vahede_andazegiri }}</td>
                                    <td>{{ ghalam.sherkat }}</td>
                                    <td>{{ ghalam.mablagh }}</td>
                                    <td>{{ ghalam.mablaghe_koll_splited }}</td>
                                </tr>
                                {% endfor %}

                            </table>
                        </tr>
                        {% endfor %}
                    </table>

                </tr>


                {% endfor %}
                <tr style="background-color-bak:#eeeeee">
                    <td style="text-align:left" colspan="9">جمع:</td>
                    <td id="ghalam_total"></td>
                    <td id="price_total"></td>

                </tr>
            </tbody>

        <tfoot>
            <tr style="background-color-bak:#eeeeee">
                <td style="text-align:left"></td>
                <td id="ghalam_total"></td>
                <td id="price_total"></td>
                <td id="price_total"></td>

            </tr>
            <tr>
                <td style="text-align:left;" colspan="12">طراحی و ساخت : مسعود عزیزی</td>

            </tr>
        </tfoot>
    </table>
    <script>
        var sum = 0;
        $('.price_totals').each(function () {
            sum += parseFloat($(this).text()); // Or this.innerHTML, this.innerText
        });
        $('#price_total').text(sum);



        var sum = 0;
        $('.sefaresh_totals').each(function () {
            sum += parseFloat($(this).text()); // Or this.innerHTML, this.innerText
        });
        $('#sefaresh_total').text(sum);


        var sum = 0;
        $('.ghalam_totals').each(function () {
            sum += parseFloat($(this).text()); // Or this.innerHTML, this.innerText
        });
        $('#ghalam_total').text(sum);


        function myFunction() {
            window.print();
        }


        $.fn.digits = function () {
            return this.each(function () {
                $(this).text($(this).text().replace(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1,"));
            })
        }

        $("td.price_totals").digits();
        $("#price_total").digits();


        $('.arzeshe_afzoode').find(':contains(True)').html('دارد');
    </script>

</body>

</html>

templates/reports/TaghazaReport.html
{% load i18n static %}
<!DOCTYPE html> {% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
<html lang="{{ LANGUAGE_CODE|default:" en-us " }}" {% if LANGUAGE_BIDI %}dir="rtl" {% endif %}>

<head>
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/base.css" %}">
    <script src="{% static "js/jquery2.min.js" %}"></script>
    <meta name="viewport" content="width=device-width,maximum-scale=1.0">
    <style>
        @media print {

            .no-print,
            .no-print * {
                display: none !important;
            }

            body {
                scale: 70%;
            }
        }

        /* table, tr {
            border-collapse:collapse;

        } */
         td,th {
            border: 2px solid #000;
            vertical-align: top;

        }

        th {
            text-align: right;
        }
        /* .taghazaTable,.taghazaTable th,.taghazaTable td {
            border: 2px solid #000;
            border-collapse: collapse;
            width: 100%;
            height: 100%;

        } */

        #ghalam_total {
            text-align: center;
            border: 1px solid #ddd;

        }
    </style>


</head>

<body style="font-family:Vazir;">

    <center class="no-print">
        گزارش مجموعه تقاضا ها
        <button onclick="myFunction()">چاپ</button>
    </center>
    <table class="taghazaTable">
        <thead>
            <tr>
                <th>ردیف</th>
                <th>شماره تقاضا</th>
                <th>واحد متقاضی</th>
                <th>شرح تقاضا</th>
                <th>مقدار</th>
                <th>تاریخ تقاضا</th>
                <!-- <th>اقلام مورد سفارش</th> -->
                <th>فاکتور</th>
                <th>مبلغ تقاضا</th>
            </tr>
            <thead>
            <tbody>
                {% for taghaza in taghazaha %}
                <tr>
                    <td> {{ taghaza.id }} </td>
                    <td> {{ taghaza.shomare }} </td>
                    <td> {{ taghaza.get_vahed_display }} </td>
                    <td> {{ taghaza.sharh }} </td>
                    <!-- <td> {{ taghaza.type }} </td> -->
                    <td> {{ taghaza.count }} </td>
                    <td> {{ taghaza.tarikh }} </td>
                    <!-- <td> {{ taghaza.linkha }} </td> -->
                    <!-- <td>
                        <table>
                            <tr>
                                <td>نام</td>
                                <td>مقدار</td>
                                <td>کدطبقه بندی کالا</td>
                            </tr>
                            {% for ghalam in taghaza.aghlam_set.all %}
                            <tr>
                                <td>{{ ghalam.kala }}</td>
                                <td class='tghalam_totals'>{{ ghalam.meghdar }}{{ ghalam.kala.vahede_andazegiri }}</td>
                                <td>{{ghalam.kala.mesc}}</td>

                            </tr>
                            {% endfor %}

                        </table>
                    </td> -->
                    <td>
                        <table>
                            <tr>
                                <td>شماره فاکتور</td>
                                <td>اقلام</td>
                                <td>تاریخ</td>
                                <td>ارزش افزوده</td>
                                <td>مقدار</td>
                                <td>مبلغ کل</td>
                            </tr>
                            {% for factor in taghaza.factor_set.all %}
                            <tr>
                                <td>{{ factor.shomare }}</td>
                                <td>
                                    <table>
                                        <tr>
                                            <td>نام</td>
                                            <td>مقدار</td>
                                            <td>فروشنده</td>
                                            <td>مبلغ</td>
                                            <td>مبلغ کل</td>
                                        </tr>
                                        {% for ghalam in factor.aghlam.all %}
                                        <tr>
                                            <td>{{ ghalam.kala }}</td>
                                            <td class='ghalam_totals'>
                                                {{ ghalam.meghdar }}{{ ghalam.kala.vahede_andazegiri }}</td>
                                            <td>{{ ghalam.sherkat }}</td>
                                            <td>{{ ghalam.mablagh }}</td>
                                            <td>{{ ghalam.mablaghe_koll_splited }}</td>
                                        </tr>
                                        {% endfor %}

                                    </table>
                                </td>
                                <td>{{ factor.tarikh }}</td>
                                <td class="arzeshe_afzoode">{{ factor.arzeshe_afzude }}</td>
                                <td>{{ factor.meghdar }}</td>
                                <td>{{ factor.price }}</td>
                            </tr>
                            {% endfor %}
                        </table>

                    </td>
                    <td class="price_totals">{{ taghaza.price }}</td>

                </tr>
                {% endfor %}
                <tr style="background-color-bak:#eeeeee">
                    <td style="text-align:left" colspan="6">جمع:</td>
                    <td id="ghalam_total"></td>
                    <td id="price_total"></td>

                </tr>
            </tbody>

        <tfoot>
            <tr>
                <td style="text-align:left;" colspan="8">طراحی و ساخت : مسعود عزیزی</td>
            </tr>
        </tfoot>
    </table>
    <script>
        var sum = 0;
        $('.price_totals').each(function () {
            sum += parseFloat($(this).text()); // Or this.innerHTML, this.innerText
        });
        $('#price_total').text(sum);



        var sum = 0;
        $('.sefaresh_totals').each(function () {
            sum += parseFloat($(this).text()); // Or this.innerHTML, this.innerText
        });
        $('#sefaresh_total').text(sum);


        var sum = 0;
        $('.ghalam_totals').each(function () {
            sum += parseFloat($(this).text()); // Or this.innerHTML, this.innerText
        });
        $('#ghalam_total').text(sum);


        function myFunction() {
            window.print();
        }


        $.fn.digits = function () {
            return this.each(function () {
                $(this).text($(this).text().replace(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1,"));
            })
        }

        $("td.price_totals").digits();
        $("#price_total").digits();


        $('.arzeshe_afzoode').find(':contains(True)').html('دارد');
    </script>

</body>

</html>

templates/reports/reports.1.html
{% block tableContent %}
<tbody>
{% comment %} Start of new taghaza {% endcomment %}
{% for taghaza in taghazaha %}
<tr>
<td> {{ taghaza.id }} </td>
<td> {{ taghaza.shomare }} </td>
<td> {{ taghaza.get_vahed_display }} </td>
<td> {{ taghaza.sharh }} </td>
<td> {{ taghaza.count }} </td>
<td> {{ taghaza.tarikh }} </td>


    {% comment %} Start of new factor {% endcomment %}
    {% for factor in taghaza.factor_set.all %}
    <td> {{ factor. }} </td>
    <td> {{ factor. }} </td>
    <td> {{ factor. }} </td>
    <td> {{ factor. }} </td>
    <td> {{ factor. }} </td>
    <td> {{ factor. }} </td>


        {% comment %} Start of new ghalam {% endcomment %}

        {% for ghalam in factor.aghlam_set.all %}
        <td> {{ ghalam. }} </td>
        <td> {{ ghalam. }} </td>
        <td> {{ ghalam. }} </td>
        <td> {{ ghalam. }} </td>
        <td> {{ ghala0m. }} </td>
        <td> {{ ghalam. }} </td>
        <td> {{ ghalam. }} </td>
        {% endfor %}


    {% endfor %}


</tr>
{% endfor %}
</tbody>
{% endblock tableContent %}